site:
  title: Site Web Cyclup
  url: https://cyclup.xyz
  start_page: Cyclup::index
  robots: allow
  keys:
    google_analytics: 'UA-176386934-1'

content:
  sources:
    # Uncomment to build from your local git clone
    - url: .
      branches: master
    # # Uncomment to build from the remote github repository.
    # - url: https://github.com/alokitetoa/cyclup.xyz.git
    
ui:
  bundle:
    # still no right menus with default ui
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    # right menus per page on H2 titles
    #url: https://deepsymmetry.org/media/antora/ui-bundle.zip
    snapshot: true

output:
  clean: true
  # for gitlab pages
  #dir: ./public
  # for github pages
  dir: ./docs

asciidoc:
  attributes:
    doctype: book
    linkattrs: 
    sectlinks: true
    icons: font
    experimental: true
    page-copyright: 2016–2020
    page-pagination: ''
    lang: fr
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true
    toc-title: Sommaire
    warning-caption: Attention
    tip-caption: Conseil
    note-caption: Info
    authors: Team Cyclup
    # substitution words
    loo: LibreOffice
    asc: Asciidoc
    pdoc: Pandoc
    notpad: Notepad{plus}{plus}
    y: icon:check[role="green"]
    n: icon:times[role="red"]
    c: icon:file-text-o[role="blue"]
    subl: Sublime Text
    vscode: Visual Studio Code

